# Generated by Django 4.1.5 on 2023-01-06 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('key_skills', models.TextField()),
                ('salary_from', models.FloatField()),
                ('salary_to', models.FloatField()),
                ('salary_currency', models.FloatField()),
                ('area_name', models.CharField(max_length=50)),
                ('published_at', models.DateTimeField()),
            ],
        ),
    ]
