# Generated by Django 4.1.5 on 2023-01-08 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0002_alter_vacancy_salary_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='salary_currency',
            field=models.CharField(max_length=4),
        ),
    ]
